In [7]:
import cv2 as cv
import copy
import numpy as np
import math
import os

In [8]:
class Star:
    def __init__(self, cx: int, cy: int, pf: float):
        self.x, self.y = cx, cy
        self.average = pf
    def __str__(self):
        return f"({self.x:.2f}, {self.y:.2f}): {self.average:.2f}"

    @property
    def x(self):
        return self._x

    @x.setter
    def x(self, value):
        self._x = value

    @property
    def y(self):
        return self._y

    @y.setter
    def y(self, value):
        self._y = value

In [9]:
def show_cv_image(img):
    cv.imshow("image", img)
    cv.waitKey(0)

def write_img(path, img):
    print(path)
    cv.imwrite(path, img)

def get_pixel_value(pixels, x: int, y: int):
    if (y >= len(pixels) or y < 0):
        return 0
    
    if (x >= len(pixels[y]) or x < 0):
        return 0

    return pixels[y][x]


def sum_within_area(pixels, x1: int, y1: int, x2: int, y2: int) -> float:
    s = 0

    if (x1 > x2):
        x1, x2 = x2, x1

    if (y1 > y2):
        y1, y2 = y2, y1

    for x in range(x1, x2+1):
        for y in range(y1, y2+1):
            s += get_pixel_value(pixels, x, y)

    return s

def compute_centroid(coords: np.ndarray):
    x, y = 0, 0

    for i in range(len(coords)):
        a = coords[i][0]
        x += a[0]
        y += a[1]

    return (x/len(coords), y/len(coords))

In [10]:
def compute_contours(path: str, intensity = 50):
    gray = cv.imread(path, cv.IMREAD_GRAYSCALE)
    ret, thresh = cv.threshold(gray, intensity, 255, 0)
    contours, hiearchy = cv.findContours(thresh, cv.RETR_TREE, cv.CHAIN_APPROX_SIMPLE)

    return contours

In [40]:
def compute_stars(path: str, draw_color = (0, 255, 0), offset = 5, directory = "tmp") -> list:
    img = cv.imread(path)
    gray = cv.cvtColor(img, cv.COLOR_BGR2GRAY)
    contours = compute_contours(path)
    stars = []

    outf = open("gray.txt", "w")
    
    for line in gray:
        outf.write("Woops! I have deleted the content!")
        print(line)


    if (not os.path.isdir(directory)):
        os.mkdir(directory)

    os.chdir(directory)

    height, width, channel = img.shape
    padding = int(offset * (math.log10(max(width, height)) * 3))
    
    for k in range(len(contours)):
        a = contours[k]

        cx, cy = compute_centroid(a)

        s = 0.0

        for k in range(len(a)):
            b = a[k][0]
            print(get_pixel_value(gray, b[0], b[1]))
            s += get_pixel_value(gray, b[0], b[1])

        s /= len(a)
        
        star = Star(cx, cy, s)
    
        stars.append(star)
    
    for k in range(len(contours)):
        star = stars[k]

        canvas = np.zeros((height + 4 * padding, width + 4 * padding, 3), np.uint8)

        highlighted = cv.drawContours(copy.copy(img), contours, k, draw_color, 3)

        canvas[2*padding:2*padding+height, 2 * padding:2 * padding+width] = highlighted

        text = cv.putText(canvas, text = str(star), org = (int(star.x) + offset - padding, int(star.y) - 2*offset + 2*padding), fontFace = cv.FONT_HERSHEY_DUPLEX, fontScale = 0.5, color = draw_color, thickness = 1)

        path = f"{k}.jpg"

        write_img(path, text)

    return stars

In [41]:
path = "/Users/yesod/Desktop/EE Data/Backyard telescope LOL/Acual Good photos/July 5.png"
s = compute_stars(path)

[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ...